import Head from 'next/head'
// import Image from 'next/image'

// import Logo from "../public/archtivate.jpeg"
// import Logo1 from "../public/archtivate-removebg-preview.png"

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import NavBar from '../components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Archtivat-Africa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/archtivate.jpeg" />
      </Head>
      <main className={styles.main}>
        <NavBar/>
        {/* <Image
          src={Logo1}
          className = {styles.logo}
        /> */}
      </main>
    </>
  )
}
